version: '3.8'

services:
  rosetta:
    image: rosetta-app:latest
    container_name: rosetta-app
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      - /opt/streamlit/rosetta:/app:ro
